### ISSUE TITLE
do not document internal variables as docstrings

### ISSUE THREAD

**Issue by jhcepas** [etetoolkit/treematcher#14]
docstrings are intended for users, so no need to provide a detailed description on how to use internal variables. Also, it is weird that function arguments are in form '__name'. I think is not necessary

**Comment by unode** [comment]
@AlishaMechtley Just to clarify, there's no harm in having detailed description on the behavior of the function even if it's internal. What is not necessary is mentioning internal variables (i.e. anything else other than the arguments passed to the function when called) as part of the docstring.

In other words, the docstring should be written keeping in mind who the target audience is and what they would want to know about this function (arguments and what it does).
