### ISSUE TITLE
command line tool

### ISSUE THREAD

**Issue by jhcepas** [etetoolkit/treematcher#17]
The command line tool is now usable, but with very basic options. 
Some more stuff should be included. For instance, options for reading target trees and pattern expressions from files, reporting matches visually or as newick, reporting just number of hits, etc..

**Comment by fransua** [comment]
The command line tool is not working for several reasons:
- the imports are not found, they should be absolute imports (as before)
- review the ways the trees are input
- review the output options (not working either)

I have commented the commits where these points were added.

we should try to run the tool before closing this issue.

**Comment by fransua** [comment]
With the integration of the treematcher into the quotedname branch, previous bugs are fixed.
However there are still some errors to correct:
-  the use of `log` does not correspond to the imported function (see solution here: https://github.com/AlishaMechtley/ete/commit/0cff1a905394abbdddfb85140622c41b73d789b4#diff-dedf954f9e60906f089c5efdaed3fdbdR3)
