### ISSUE TITLE
review unit tests

### ISSUE THREAD

**Issue by jhcepas** [etetoolkit/treematcher#20]
While refactoring I found a few test cases that where returning True when actually the result was incorrect. Let's try to double check all the unitests little by little.
It is very important that we can trust them

**Comment by AlishaMechtley** [comment]
All the unittests have been checked

**Comment by jhcepas** [comment]
I only reviewed a couple that were failing after refactoring. Checks still needed for the rest :)

**Comment by AlishaMechtley** [comment]
I check all of them and added lines that check for the specific nodes that should be returned.
