### ISSUE TITLE
relaxed matches (regular expression like syntax)

### ISSUE THREAD

**Issue by jhcepas** [etetoolkit/treematcher#22]
some proposals for the relaxed matching syntax (using Perl symbols):

Find nodes where (a,b) is connected to (c,d) by one or more intermediate parent nodes:

```
( ((a,b))+, (c,d));
```

Find nodes where (a,b) and (c,d) exist in the same tree connected by any number of nodes:

```
( ((a,b))*, ((c,d))*);
```

Ideally, this should also allow us to combine with basic node searches. For instance, find nodes where (a,b) is connected to (c,d), by one or more duplication parent nodes:

```
( ((a,b))'+is_duplication(@) == True', (c,d));
```

Syntax looks ugly, I know, but once the functionality is in place we could think of a more readable method

**Comment by DimitrisPl** [comment]
Some unittests to better describe the wildcards functionality. It covers some basic symbols (*, +, ^, $).

[regExp_TreematcherTest.py.txt](https://github.com/etetoolkit/treematcher/files/933259/regExp_TreematcherTest.py.txt)
