### ISSUE TITLE
Incomplete Code Segment in ete_treematcher.py

### ISSUE THREAD

**Issue by djokester** [etetoolkit/treematcher#23]
In line number 156 the code is like this 
`if li                yield line `
which doesn't make any sense!

**Comment by unode** [comment]
Hi @djokester 

Well spotted and also a syntax error.
Clearly a typo that went by unnoticed. [Before it read like this](https://github.com/etetoolkit/treematcher/commit/e702922e148442adc41cb13c2e252302257748a5#diff-36cb39a2b4d91d5bba98bdccba373cf9L154).

Thanks!
