### ISSUE TITLE
find_match should be an iterator returning all found matches.

### ISSUE THREAD

**Issue by fransua** [etetoolkit/treematcher#3]
_find_match_ function now return only the first match of the queried pattern.
Ideally this function would **yield** all the matches, and could have a parameter to limit the number of matches the user may want.

something like: 
`find_match(self, tree, local_vars, maxhits=1)`

**Comment by AlishaMechtley** [comment]
I have been keeping the Python 2/3 compatibility inspection on in PyCharm and I try to address compatibility issues as they arise. None of the code so far has required six except in the ete_treematcher.py (the command line tool) but I imagine I'll use six more as the code progresses.
