### ISSUE TITLE
check and improve `ete search` tool 

### ISSUE THREAD

**Issue by jhcepas** [etetoolkit/treematcher#42]
basic functionality of the treematcher module should be accessible from the API through an ete tool called ete-search which should be implemented as `ete_search.py`

Desired features:

- [x] review and close this issue: https://github.com/etetoolkit/treematcher/issues/17
- [x] read newick pattern from the command line as newick string or from a file
- [x] read target trees from the command line as newick strings or from a files
- [x] dump matches in newick format or print them as ascii art
- [ ] any other stuff here?

**Comment by dpliakos** [comment]
What about:
-h, --hide     | do no print anything ( can be combined with --verbose to show only stats about the results)
-f. --format  | choose the format of the trees / pattern (both the same). 

--first |while reading a file stop at the first match that found.

**Comment by dpliakos** [comment]
Old command line tool was updated and replace that one.
