### ISSUE TITLE
python 2/3 compatibility

### ISSUE THREAD

**Issue by jhcepas** [etetoolkit/treematcher#5]
Make sure code is python 2/3 compatible. ETE uses the module six for keeping compatible syntax

**Comment by AlishaMechtley** [comment]
Treematcher is currently uses six and is python 2/3 compatible. I have been keeping the Python 2/3 compatibility inspection on in PyCharm and I try to address compatibility issues as they arise using six.

**Comment by unode** [comment]
@AlishaMechtley has this been pushed?
I don't see the changes.

**Comment by unode** [comment]
@AlishaMechtley If you are still committing the code, have a look at the closing note of this issue: https://github.com/etetoolkit/ete/issues/206 and the corresponding commit message: https://github.com/etetoolkit/ete/commit/e27e71f3bfc1de1969948cdf3718d91cfee59492 .
This makes is easier for anyone reading the issue to check the code changes.

Cheers,
Renato
