### ISSUE TITLE
docstring documentation is missing in TreeMatcher class and functions.

### ISSUE THREAD

**Issue by jhcepas** [etetoolkit/treematcher#8]

**Comment by fransua** [comment]
in order for sphinx to automaticaly generate the documentation from your docstring (understanding what parameters are there, with which default values etc..), you should follow a simple scheme as the one we already use in ETE, here an example:
https://github.com/etetoolkit/ete/blob/master/ete3/evol/model.py#L275

**Comment by fransua** [comment]
@AlishaMechtley : the documentation should be extended, a description of what does the function should appear before the description of the parameters.
This is perhaps not necessary for all the functions, but at least for the main ones.
